CREATE ROLE user WITH LOGIN PASSWORD 'XXXXXXXXXXXX' NOCREATEDB NOCREATEROLE;
GRANT CREATE ON SCHEMA public TO user;
GRANT USAGE ON SCHEMA public TO user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO user;

ALTER DATABASE db OWNER to user;
GRANT user TO root;
REASSIGN OWNED BY root TO user;


